export const GET_CONTACTS = "GET_CONTACTS";
export const SET_ERROR = 'SET_ERROR';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_PAGINATION = 'SET_PAGINATION';
export const GET_SINGLE_CONTACT = 'GET_SINGLE_CONTACT';
export const CLEAR_SINGLE_CONTACT = 'CLEAR_SINGLE_CONTACT';
